# Generated by Django 5.0.7 on 2024-07-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_transaction_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
