# Generated by Django 5.0.7 on 2024-07-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_transaction_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='mintuser',
            name='otp',
            field=models.IntegerField(default=7777),
        ),
    ]
